version: "3"
services:
  node:
    # image: "node:8"
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    # command: "npm build"
    # command: "/bin/bash"
    # command: "echo ${SHELL}"