version: '3.9'

services: 
  db1: 
    container_name: db1
    hostname: db1
    image: mariadb:latest
    volumes: 
      # - ${PWD}/db1/dbs/:/var/lib/mysql
      - data:/var/lib/mysql
      # - ${PWD}/db1/conf/:/etc/mysql
      # - ${PWD}/db1/mydata/:/mydata
    networks: 
      default: 
        ipv4_address: 172.27.0.1
    ports: 
      - "127.0.0.1:33061:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: mydbpass

volumes: 
  data: 
    driver: local

networks: 
  default: 
    external: true
    name: mybr0
